name: Valgrind & Clang Tester

on:
    - push

jobs:
    run_valgrind_tests:
        runs-on: ubuntu-latest
        steps:
            -   name: "Checkout"
                uses: actions/checkout@v4.1.4

            -   name: "Compile tests"
                run: |
                    gcc -g tests/test_invalid_free.c -o test_invalid_free
                    gcc -g tests/test_invalid_read.c -o test_invalid_read
                    gcc -g tests/test_invalid_write.c -o test_invalid_write
                    gcc -g tests/test_no_free.c -o test_no_free
                    gcc -g tests/test_realloc_zero.c -o test_realloc_zero
                    gcc -g tests/test_unclosed_file_descriptor.c -o test_unclosed_file_descriptor

            -   name: "Valgrind test_invalid_free"
                uses: ./
                with:
                    binary_path: "./test_invalid_free"
                    treat_error_as_warning: true

            -   name: "Valgrind test_invalid_read"
                uses: ./
                with:
                    binary_path: "./test_invalid_read"
                    treat_error_as_warning: true

            -   name: "Valgrind test_invalid_write"
                uses: ./
                with:
                    binary_path: "./test_invalid_write"
                    treat_error_as_warning: true

            -   name: "Valgrind test_no_free"
                uses: ./
                with:
                    binary_path: "./test_no_free"
                    treat_error_as_warning: true

            -   name: "Valgrind test_realloc_zero"
                uses: ./
                with:
                    binary_path: "./test_realloc_zero"
                    treat_error_as_warning: true

            -   name: "Valgrind test_unclosed_file_descriptor"
                uses: ./
                with:
                    binary_path: "./test_unclosed_file_descriptor"
                    treat_error_as_warning: true

    run_clang_tests:
        runs-on: ubuntu-latest
        steps:
            -   name: "Checkout"
                uses: actions/checkout@v4.1.4

            -   name: "Clang ASan test"
                uses: ./
                with:
                    mode: clang
                    source_files: "tests/test_clang_asan.c"
                    sanitizer: asan
                    treat_error_as_warning: true

            -   name: "Clang UBSan test"
                uses: ./
                with:
                    mode: clang
                    source_files: "tests/test_clang_ubsan.c"
                    sanitizer: ubsan
                    treat_error_as_warning: true

            -   name: "Clang TSan test"
                uses: ./
                with:
                    mode: clang
                    source_files: "tests/test_clang_tsan.c"
                    sanitizer: tsan
                    clang_extra_flags: "-pthread"
                    treat_error_as_warning: true

            -   name: "Clang MSan test"
                uses: ./
                with:
                    mode: clang
                    source_files: "tests/test_clang_msan.c"
                    sanitizer: msan
                    treat_error_as_warning: true

            -   name: "Clang LSan test"
                uses: ./
                with:
                    mode: clang
                    source_files: "tests/test_clang_lsan.c"
                    sanitizer: lsan
                    treat_error_as_warning: true

            -   name: "Clang++ ASan test (C++)"
                uses: ./
                with:
                    mode: clang
                    compiler: clang++
                    source_files: "tests/test_clang_asan.cpp"
                    sanitizer: asan
                    treat_error_as_warning: true

    run_clang_tidy_tests:
        runs-on: ubuntu-latest
        steps:
            -   name: "Checkout"
                uses: actions/checkout@v4.1.4

            -   name: "Clang-Tidy test"
                uses: ./
                with:
                    mode: clang-tidy
                    source_files: "tests/test_clang_tidy.c"
                    treat_error_as_warning: true

    run_iwyu_tests:
        runs-on: ubuntu-latest
        steps:
            -   name: "Checkout"
                uses: actions/checkout@v4.1.4

            -   name: "IWYU test"
                uses: ./
                with:
                    mode: iwyu
                    source_files: "tests/test_iwyu.c"
                    treat_error_as_warning: true
